# Generated by Django 3.0.3 on 2020-09-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('accounts', '0002_auto_20200913_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to='job.Job'),
        ),
    ]
