# Generated by Django 3.0.3 on 2020-09-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jobs',
        ),
    ]
