# Generated by Django 3.0.3 on 2020-09-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200916_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='job.Job'),
        ),
    ]
