# Generated by Django 3.0.3 on 2020-09-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_categories_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='job',
        ),
    ]
