# Generated by Django 3.0.3 on 2020-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200919_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(related_name='jobs', to='job.Categories'),
        ),
    ]
